### ISSUE TITLE
Automation E2E (end-to-end) testing on android & iOs with Ionic, protractor & Appium | Test case

### ISSUE THREAD

**Issue by SathishkumarG3** [dollarshaveclub/e2e#42]
When attempting to run **npm run e2e** in an Ionic application, we encounter the following error. To resolve this, we need to examine the dependencies and configuration.
Environment Details:

- Node Version: v16.14.0
- Protractor Version: 7.0.0
- Angular Version: v16.14.0
- Browser(s): Chrome Version 125.0.6422.113 (Official Build) (64-bit)
- Operating System: Windows 11

**Error Details:**

`PS C:\Users\SathishkumarG\Downloads\AppiumTestCase> npm run e2e

> photo-gallery-ng-capacitor@2.0.0 e2e
> ng e2e

Protractor has been deprecated including its support in the Angular CLI. For additional information and alternatives, please see https://github.com/angular/protractor/issues/5502.
[12:58:15] I/update - chromedriver: file exists C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webdriver-manager\selenium\chromedriver_114.0.5735.90.zip
[12:58:15] I/update - chromedriver: unzipping chromedriver_114.0.5735.90.zip
[12:58:15] I/update - chromedriver: chromedriver_114.0.5735.90.exe up to date
⠧ Generating browser application bundles (phase: building)...node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\node_modules\webpack-sources\lib\RawSource.js:77:8)
    at NormalModule._initBuildHash (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\NormalModule.js:880:17)
    at handleParseResult (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\NormalModule.js:946:10)
    at C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\NormalModule.js:1040:4
    at processResult (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\NormalModule.js:755:11)
    at C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\webpack\lib\NormalModule.js:819:5
    at C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\loader-runner\lib\LoaderRunner.js:407:3
    at iterateNormalLoaders (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\loader-runner\lib\LoaderRunner.js:233:10)
    at iterateNormalLoaders (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\loader-runner\lib\LoaderRunner.js:240:10)
    at C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\loader-runner\lib\LoaderRunner.js:255:3
    at context.callback (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\Users\SathishkumarG\Downloads\AppiumTestCase\node_modules\postcss-loader\dist\index.js:195:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.19.0`

**Comment by SathishkumarG3** [comment]
Please prioritize this as we are still facing the same issue. If any channels are available, please provide updates
